### ISSUE TITLE
Add support for :for and :let attrs

### ISSUE THREAD

**Issue by connorlay** [phoenixframework/tree-sitter-heex#12]
See https://github.com/phoenixframework/phoenix_live_view/pull/2023 and https://github.com/phoenixframework/phoenix_live_view/pull/2013 for more information.

**Comment by josevalim** [comment]
We will also have `:stream` in the future. So we should either include it or make the rule general for all attributes starting with `:`?

**Comment by the-mikedavis** [comment]
I think we could make a small change to the queries for this:

```scm
((attribute_name) @keyword
 (#match? "^:" @keyword))

(attribute_name) @attribute
```

**Comment by connorlay** [comment]
@josevalim @the-mikedavis Are there any constraints on which tags can have these attributes that start with a colon? If so, do we want that rule enforced by the grammar?

For example, the way slots are implemented require them to be a child of a function component: https://github.com/phoenixframework/tree-sitter-heex/blob/57e46b4b002d5fb5c1f2706fe42380e544ecab5f/grammar.js#L38

I don't have a strong opinion either way, so I'm curious what you two think 🙂

**Comment by josevalim** [comment]
:let is on components and slots. :for and :stream are only on HTML tags.

**Comment by the-mikedavis** [comment]
I think I lean towards building them into the parser given that they're only valid in certain tags and there are so few of them. On the other hand, `:` attributes are special in other front-end frameworks like Vue so I don't see much harm in highlighting them all differently from regular attributes. I'm not sure 😅

**Comment by connorlay** [comment]
Implemented by https://github.com/phoenixframework/tree-sitter-heex/pull/16
