### ISSUE TITLE
New to TS - Unable to install heex

### ISSUE THREAD

**Issue by fkumro** [phoenixframework/tree-sitter-heex#2]
Hi,

I'm using neovim and tree-sitter but ran into an issue when trying to install heex.

```bash
:TSInstall heex
Parser not available for language heex
```

Any ideas on what could be wrong with my system? I was able to use `:TSInstall` to install elixir/erlang/html grammar, so *something* works.

Thanks!!

**Comment by connorlay** [comment]
Hello! What version of neovim and tree-sitter are you using? It looks like the grammar needs to be back-ported from nvim-treesitter `master` to `0.5-compat`. I can take a look into what that will entail. In the meantime, if you switch to neovim nightly and the `master` branch of nvim-treesitter, I think things should work for you.

**Comment by fkumro** [comment]
That was the issue! Lunarvim uses `0.5-compat` for TS. Thank you 🙏

**Comment by connorlay** [comment]
@fkumro Looks like once https://github.com/nvim-treesitter/nvim-treesitter/pull/1808 is merged you'll have access to HEEx from LunarVim.
