### ISSUE TITLE
Indentation and `Pair Matching` not working

### ISSUE THREAD

**Issue by heimann** [phoenixframework/tree-sitter-heex#3]
Hi!

First of all, thank you for putting this together so close to the release of LV 0.16 I was so stoked when I saw there was treesitter support already ❤️ 

I'm having some issues where indentation motions with `=` are just putting everything flat on the same level, and the `%` motion to go to a "matching pair" which I expect _should_ take me to the closing take for a div for example if I'm on the opening tag, isn't working. It's just doing nothing. 

Odds are my configuration are just wrong, any ideas on how to trouble shoot this most effectively?

**Comment by heimann** [comment]
Ok I realized I just had to set indent = true in my treesitter config for that to work. Any idea what I'd need to do to get pair matching working? I can't find a reference to it in the treesitter docs.

**Comment by connorlay** [comment]
Hi @heimann , thanks for the feedback!

For indentation, you are correct: the corresponding nvim-treesitter indentation module must be enabled for the `=` operator to work with treesitter.

As for `%` matching, I did a bit of research and it looks like the following options are available:
1) Install the [nvim-treesitter-pairs](https://github.com/theHamsta/nvim-treesitter-pairs) external module and add a `pairs.scm` file for HEEx. Here is an example for [html](https://github.com/theHamsta/nvim-treesitter-pairs/blob/master/queries/html/pairs.scm).
2) Define a vim [matchpairs](https://neovim.io/doc/user/options.html#'matchpairs') value for HEEx. The [vim-elixir](https://github.com/elixir-editors/vim-elixir/blob/master/ftplugin/eelixir.vim) would be a good reference for getting this to work.

Regardless of which route you pick, I'd like to keep this issue open to track the status of the `%` integration with HEEx and Neovim. It might be worth asking in the main [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter) repository as well... I'm sure this question has come up before with new grammars 🤔

**Comment by connorlay** [comment]
https://github.com/nvim-treesitter/nvim-treesitter/pull/2415 improved indentation support in nvim-treesitter. For the `%` operator, there are a couple paths available (see my earlier comment) that don't require changes to the grammar itself.
