### ISSUE TITLE
Support for ~F sigil? :)

### ISSUE THREAD

**Issue by noozo** [phoenixframework/tree-sitter-heex#30]
Thank you for this parser. Are you planning to support ~F, now that ~H is deprecated? Cheers!

**Comment by josevalim** [comment]
~F is not used by Phoenix :)

**Comment by connorlay** [comment]
@noozo For `~F` support there is [tree-sitter-surface](https://github.com/connorlay/tree-sitter-surface) that supports version 0.5 of the Surface template syntax.
