### ISSUE TITLE
Directives are not parsed any further (i.e. expressions must be parsed manually)

### ISSUE THREAD

**Issue by dhorkin** [phoenixframework/tree-sitter-heex#32]
Suppose you have input like so:
`<%= link "manage", to: Routes.apps_path(@conn, :app_index, app.id), class: "btn-lik", "data-test": "manage_link" %>`

This produces a tree with `(fragment (directive (expression_value)))`

My goal in this case is to pull out the `manage_link`, but I have to manually parse the expression to get what I want:

```ts
const query = parser.getLanguage().query(`
  directive 
    (expression_value) @expression
    (#match? @expression "data-test")
  )
`);

  const matchingValues = captures.map(c => c.node.text.match(/(['"])data-test\1:\s*(['"])(.*)\2/)?.[3]);
```

This feels pretty brittle; there ought to be a way to do a query along the lines of
```
((directive
  (expression_value
    (expression_attribute
      (attribute_name) @attribute-name
      (quoted_attribute_value
        (attribute_value) @attribute-value
      ))
  (#eq? @attribute-name "data-test")
)
```

**Comment by the-mikedavis** [comment]
This is intentional: this parser only parses the HEEx part of the syntax and then the Elixir parts can be parsed by tree-sitter-elixir. In tree-sitter consumers like editors this uses [language injection](https://tree-sitter.github.io/tree-sitter/syntax-highlighting#language-injection).

**Comment by dhorkin** [comment]
> This is intentional: this parser only parses the HEEx part of the syntax and then the Elixir parts can be parsed by tree-sitter-elixir. In tree-sitter consumers like editors this uses [language injection](https://tree-sitter.github.io/tree-sitter/syntax-highlighting#language-injection).

thanks for pointing me in the right direction

**Comment by dhorkin** [comment]
It seems to know that it's supposed to interpret as elixir, but it isn't further parsing elixir. I haven't been able to find anything concrete on using language injection beyond the query syntax - how do I tell tree-sitter where to find Elixir if my parser language is Heex?

This:
```js
  const query = parser.getLanguage().query(`
    ( directive
      (
        (expression_value) @injection.content
          (#set! injection.language "elixir")
        )
    )
  `);

     console.log(query.captures(tree.rootNode));
```
shows that matching nodes have `setProperties: { 'injection.language': 'elixir' }`

But if I try to use Elixir in the query, it fails with `RangeError: Bad node name 'pair'`:
```js
  const query = parser.getLanguage().query(`
    ( directive
      (
        ((expression_value) @injection.content
          (#set! injection.language "elixir")
          (pair key: 
            (quoted_keyword
              (quoted_content) @attribute-name
            )
            value: (
              string (quoted_content) @attribute-value
            )
          )))
      )
    )
  `);
```

**Comment by the-mikedavis** [comment]
You won't be able to combine HEEx and Elixir queries in the same query string. I'm not very familiar with the node bindings for tree-sitter but I believe it doesn't help you with injections (AFAIK injections are mostly a convention from the tree-sitter-highlight crate https://github.com/tree-sitter/tree-sitter/tree/master/highlight). So you'll need to query HEEx first, find the ranges of the input that are Elixir, for example `(expression_value)`s, and then parse and queries those ranges with tree-sitter-elixir.
