### ISSUE TITLE
freature request: sigil-H support?

### ISSUE THREAD

**Issue by briandunn** [phoenixframework/tree-sitter-heex#4]
Thanks for this lib! now my `html.heex` files are a lot more readable. Are you planning on implementing support for `~H` heex regions? I'm interested in helping out with this, seems like it may relate to this call https://github.com/neovim/neovim/blob/master/runtime/lua/vim/treesitter/languagetree.lua#L263.

**Comment by connorlay** [comment]
Hi @briandunn, are you referring to language injection for syntax highlighting? If so, that is currently supported via the [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/elixir/injections.scm) plugin. What version of neovim and nvim-treesitter are you using?

This is what it looks like for me on neovim nightly and nvim-treesitter master:
![image](https://user-images.githubusercontent.com/6548350/136729570-a8d0c9ff-8931-4238-9d04-e8f4206baec0.png)

**Comment by briandunn** [comment]
Just needed to `TSInstall elixir` and now it works! Thanks @connorlay.
