### ISSUE TITLE
Error on `do` blocks

### ISSUE THREAD

**Issue by mhanberg** [phoenixframework/tree-sitter-heex#6]
I created a vanilla phx project and created a new resource using the generators and I am seeing an error on the `do` in do blocks.

Here you can see the screenshot with the corresponding nodes in nvim treesitter playground.

<img width="2032" alt="image" src="https://user-images.githubusercontent.com/5523984/140444602-125d917c-8493-4d72-be2f-c5c948f09fb8.png">

**Comment by mhanberg** [comment]
Also doesn't seem to be working here either

<img width="2032" alt="image" src="https://user-images.githubusercontent.com/5523984/140445195-48a9bc68-a7d4-4624-b9f3-e6afa661d595.png">

I am on neovim master as like 30 minutes ago (i'm not sure the exact hash)

**Comment by mhanberg** [comment]
This might be a problem with neovim as of right now. I'll close this for now since i'm not sure.

**Comment by connorlay** [comment]
Hi @mhanberg , thanks for the bug report! IIRC this is an issue with combined code injection in nvim-treesitter, see https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/heex/injections.scm for how to enable this.
